language: php

before_script:
    - composer install
    - echo 'short_open_tag = On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - mysql -e 'CREATE DATABASE concrete5;'
    - vendor/bin/install-concrete5.php --db-server=localhost --db-username=travis --db-database=concrete5 --admin-email=webmaster@example.org --admin-password=password --target=../../../web --starting-point=standard

script: vendor/bin/phpunit

notifications:
    email: false
